--CREATE DATABASE

USE master;
GO

IF DB_ID (N'RetoolSampleDataDB') IS NOT NULL
BEGIN
	ALTER DATABASE RetoolSampleDataDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE RetoolSampleDataDB
END

CREATE DATABASE RetoolSampleDataDB;
GO

--CREATE TABLE
USE [RetoolSampleDataDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NationalParkList](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[park_name] [nvarchar](50) NULL,
	[park_state] [nvarchar](50) NULL,
	[park_code] [nvarchar](60) NULL,
	[park_visitors] [int] NULL,
	[park_description] [nvarchar](max) NULL,
	[nps_link] [nvarchar](max) NULL,
	[park_date_est] [date] NULL,
	[park_lat] [decimal](8, 6) NULL,
	[park_long] [decimal](9, 6) NULL,
	[park_area_acres] [decimal](9, 2) NULL,
	[park_area_sq_km] [decimal](9, 2) NULL,
	[pic_license] [nvarchar](max) NULL,
	[pic_url] [nvarchar](max) NULL,
 CONSTRAINT [PK_NationalParkList] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




--INSERT ROWS
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (49057.36,198.50,44.35,-68.21,'2/26/1919','Covering most of Mount Desert Island and other coastal islands, Acadia features the tallest mountain on the Atlantic coast of the United States, granite peaks, ocean shoreline, woodlands, and lakes. There are freshwater, estuary, forest, and intertidal habitats.','https://www.nps.gov/acad/index.htm','Maine','Acadia','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Acadia_National_Park_02.JPG/320px-Acadia_National_Park_02.JPG','park_acadia',3303393);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (8256.67,33.40,-14.25,-170.68,'10/31/1988','The southernmost National Park is on three Samoan islands and protects coral reefs, rainforests, volcanic mountains, and white beaches. The area is also home to flying foxes, brown boobies, sea turtles, and 900 species of fish.','https://www.nps.gov/npsa/index.htm','American Samoa','American Samoa','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Vatia_from_the_National_Park_of_American_Samoa.jpg/320px-Vatia_from_the_National_Park_of_American_Samoa.jpg','park_american-samoa',28892);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (76678.98,310.30,38.68,-109.57,'11/12/1971','This site features more than 2,000 natural sandstone arches, with some of the most popular arches in the park being Delicate Arch, Landscape Arch and Double Arch. Millions of years of erosion have created these structures located in a desert climate where the arid ground has life-sustaining biological soil crusts and potholes that serve as natural water-collecting basins. Other geologic formations include stone pinnacles, fins, and balancing rocks.','https://www.nps.gov/arch/index.htm','Utah','Arches','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Delicatearch.png/317px-Delicatearch.png','park_arches',1585718);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (242755.94,982.40,43.75,-102.5,'11/10/1978','The Badlands are a collection of buttes, pinnacles, spires, and mixed-grass prairies. The White River Badlands contain the largest assemblage of known late Eocene and Oligocene mammal fossils. The wildlife includes bison, bighorn sheep, black-footed ferrets, and prairie dogs.','https://www.nps.gov/badl/index.htm','South Dakota','Badlands','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MK00609_Badlands.jpg/320px-MK00609_Badlands.jpg','park_badlands',996263);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (801163.21,3242.20,29.25,-103.25,'6/12/1944','Named for the prominent bend in the Rio Grande along the U.S.–Mexico border, this park encompasses a large and remote part of the Chihuahuan Desert. Its main attraction is backcountry recreation in the arid Chisos Mountains and in canyons along the river. A wide variety of Cretaceous and Tertiary fossils as well as cultural artifacts of Native Americans also exist within its borders.','https://www.nps.gov/bibe/index.htm','Texas','Big Bend','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Big_Bend_Chihuahuan_Desert.jpg/320px-Big_Bend_Chihuahuan_Desert.jpg','park_big-bend',388290);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (172971.11,700.00,25.65,-80.08,'6/28/1980','Located in Biscayne Bay, this park at the north end of the Florida Keys has four interrelated marine ecosystems: mangrove forest, the Bay, the Keys, and coral reefs. Threatened animals include the West Indian manatee, American crocodile, various sea turtles, and peregrine falcon.','https://www.nps.gov/bisc/index.htm','Florida','Biscayne','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Biscayne.JPG/320px-Biscayne.JPG','park_biscayne',514709);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (30749.75,124.40,38.57,-107.72,'10/21/1999','The park protects a quarter of the Gunnison River, which slices sheer canyon walls from dark Precambrian-era rock. The canyon features some of the steepest cliffs and oldest rock in North America, and is a popular site for river rafting and rock climbing. The deep, narrow canyon is composed of gneiss and schist which appears black when in shadow.','https://www.nps.gov/blca/index.htm','Colorado','Black Canyon of the Gunnison','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Black_Canyon_and_Gunnison_River_2008.jpg/320px-Black_Canyon_and_Gunnison_River_2008.jpg','park_black-canyon-of-the-gunnison',238018);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (35835.08,145.00,37.57,-112.18,'2/25/1928','Bryce Canyon is a geological amphitheater on the Paunsaugunt Plateau with hundreds of tall, multicolored sandstone hoodoos formed by erosion. The region was originally settled by Native Americans and later by Mormon pioneers.','https://www.nps.gov/brca/index.htm','Utah','Bryce Canyon','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Inspiration_Point_Bryce_Canyon_November_2018_panorama.jpg/320px-Inspiration_Point_Bryce_Canyon_November_2018_panorama.jpg','park_bryce-canyon',2365110);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (337597.83,1366.20,38.2,-109.93,'9/12/1964','This landscape was eroded into a maze of canyons, buttes, and mesas by the combined efforts of the Colorado River, Green River, and their tributaries, which divide the park into three districts. The park also contains rock pinnacles and arches, as well as artifacts from Ancient Pueblo peoples.','https://www.nps.gov/cany/index.htm','Utah','Canyonlands','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Green_River_Overlook_Ekker_Butte.jpg/320px-Green_River_Overlook_Ekker_Butte.jpg','park_canyonlands',776218);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (241904.26,979.00,38.2,-111.17,'12/18/1971','The park''s Waterpocket Fold is a 100-mile (160 km) monocline that exhibits the earth''s diverse geologic layers. Other natural features include monoliths, cliffs, and sandstone domes shaped like the United States Capitol.','https://www.nps.gov/care/index.htm','Utah','Capitol Reef','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Capitol_Reef_National_Park.jpg/320px-Capitol_Reef_National_Park.jpg','park_capitol-reef',1064904);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (46766.45,189.30,32.17,-104.44,'5/14/1930','Carlsbad Caverns has 117 caves, the longest of which is over 120 miles (190 km) long. The Big Room is almost 4,000 feet (1,200 m) long, and the caves are home to over 400,000 Mexican free-tailed bats and sixteen other species. Above ground are the Chihuahuan Desert and Rattlesnake Springs.','https://www.nps.gov/cave/index.htm','New Mexico','Carlsbad Caverns','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Carlsbad_Caverns_Entrance.jpg/320px-Carlsbad_Caverns_Entrance.jpg','park_carlsbad-caverns',466773);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (249561.00,1009.90,34.01,-119.42,'3/5/1980','Five of the eight Channel Islands are protected, and half of the park''s area is underwater. The islands have a unique Mediterranean ecosystem originally settled by the Chumash people. They are home to over 2,000 species of land plants and animals, and 145 are unique to them, including the island fox. Ferry services offer transportation to the islands from the mainland.','https://www.nps.gov/chis/index.htm','California','Channel Islands','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Channel_Islands_National_Park_by_Sentinel-2.jpg/320px-Channel_Islands_National_Park_by_Sentinel-2.jpg','park_channel-islands',364807);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (26275.82,106.30,33.78,-80.78,'11/10/2003','On the Congaree River, this park is the largest portion of old-growth floodplain forest left in North America. Some of the trees are the tallest in the eastern United States. An elevated walkway called the Boardwalk Loop guides visitors through the swamp.','https://www.nps.gov/cong/index.htm','South Carolina','Congaree','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Kayakers_on_Cedar_Creek.jpg/228px-Kayakers_on_Cedar_Creek.jpg','park_congaree',143843);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (183224.05,741.50,42.94,-122.1,'5/22/1902','Crater Lake lies in the caldera of an ancient volcano called Mount Mazama that collapsed 7,700 years ago. It is the deepest lake in the United States and is noted for its vivid blue color and water clarity. There are two more recent volcanic islands in the lake, and, with no inlets or outlets, all water comes through precipitation.','https://www.nps.gov/crla/index.htm','Oregon','Crater Lake','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Kayakers_on_Cedar_Creek.jpg/228px-Kayakers_on_Cedar_Creek.jpg','park_crater-lake',756344);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (32572.35,131.80,41.24,-81.55,'10/11/2000','This park along the Cuyahoga River has waterfalls, hills, trails, and exhibits on early rural living. The Ohio and Erie Canal Towpath Trail follows the Ohio and Erie Canal, where mules towed canal boats. The park has numerous historic homes, bridges, and structures, and also offers a scenic train ride.','https://www.nps.gov/cuva/index.htm','Ohio','Cuyahoga Valley','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Cuyahoga_Valley_National_Park.jpg/319px-Cuyahoga_Valley_National_Park.jpg','park_cuyahoga-valley',2423390);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (3373063.14,13650.30,36.24,-116.82,'10/31/1994','Death Valley is the hottest, lowest, and driest place in the United States. Daytime temperatures have topped 130 °F (54 °C) and it is home to Badwater Basin, the lowest elevation in North America. The park contains canyons, badlands, sand dunes, and mountain ranges, while more than 1000 species of plants grow in this geologic graben. Additional points of interest include salt flats, historic mines, and springs.','https://www.nps.gov/deva/index.htm','California','Death Valley','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Sand_Dunes_in_Death_Valley_National_Park.jpg/320px-Sand_Dunes_in_Death_Valley_National_Park.jpg','park_death-valley',1296283);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (4740911.16,19185.80,63.33,-150.5,'2/26/1917','Centered on Denali, the tallest mountain in North America, Denali is serviced by a single road leading to Wonder Lake. Denali and other peaks of the Alaska Range are covered with long glaciers and boreal forest. Wildlife includes grizzly bears, Dall sheep, caribou, and gray wolves.','https://www.nps.gov/dena/index.htm','Alaska','Denali','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Every_Road-_Denali_%287945497984%29.jpg/320px-Every_Road-_Denali_%287945497984%29.jpg','park_denali',587412);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (64701.22,261.80,24.63,-82.87,'10/26/1992','The islands of the Dry Tortugas, at the westernmost end of the Florida Keys, are the site of Fort Jefferson, a Civil War-era fort that is the largest masonry structure in the Western Hemisphere. With most of the park being remote ocean, it is home to undisturbed coral reefs and shipwrecks and is only accessible by plane or boat.','https://www.nps.gov/drto/index.htm','Florida','Dry Tortugas','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Fort-Jefferson_Dry-Tortugas.jpg/320px-Fort-Jefferson_Dry-Tortugas.jpg','park_dry-tortugas',73661);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (1508968.10,6106.60,25.32,-80.93,'5/30/1934','The Everglades are the largest tropical wilderness in the United States. This mangrove and tropical rainforest ecosystem and marine estuary is home to 36 protected species, including the Florida panther, American crocodile, and West Indian manatee. Some areas have been drained and developed; restoration projects aim to restore the ecology.','https://www.nps.gov/ever/index.htm','Florida','Everglades','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sunset_over_the_River_of_Grass%2C_NPSphoto%2C_G.Gardner_%289255157507%29.jpg/320px-Sunset_over_the_River_of_Grass%2C_NPSphoto%2C_G.Gardner_%289255157507%29.jpg','park_everglades',930907);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (7523897.45,30448.10,67.78,-153.3,'12/2/1980','The country''s northernmost park protects an expanse of pure wilderness in Alaska''s Brooks Range and has no park facilities. The land is home to Alaska Natives who have relied on the land and caribou for 11,000 years.','https://www.nps.gov/gaar/index.htm','Alaska','Gates of the Arctic','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Oolah_Valley_%2816089307144%29.jpg/320px-Oolah_Valley_%2816089307144%29.jpg','park_gates-of-the-arctic',10047);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (1013128.94,4100.00,48.8,-114,'5/11/1910','The U.S. half of Waterton-Glacier International Peace Park, this park includes 26 glaciers and 130 named lakes surrounded by Rocky Mountain peaks. There are historic hotels and a landmark road called the Going-to-the-Sun Road in this region of rapidly receding glaciers. The local mountains, formed by an overthrust, expose Paleozoic fossils including trilobites, mollusks, giant ferns and dinosaurs.','https://www.nps.gov/glac/index.htm','Montana','Glacier','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Mountain_Goat_at_Hidden_Lake.jpg/320px-Mountain_Goat_at_Hidden_Lake.jpg','park_glacier',2946681);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (3223383.43,13044.60,58.5,-137,'12/2/1980','Glacier Bay contains tidewater glaciers, mountains, fjords, and a temperate rainforest, and is home to large populations of grizzly bears, mountain goats, whales, seals, and eagles. When discovered in 1794 by George Vancouver, the entire bay was covered by ice, but the glaciers have since receded more than 65 miles (105 km).','https://www.nps.gov/glba/index.htm','Alaska','Glacier Bay','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/archive/b/bf/20151222083444%21A045%2C_Glacier_Bay_National_Park%2C_Alaska%2C_USA%2C_Johns_Hopkins_Glacier%2C_2002.jpg','park_glacier-bay',520171);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (1201647.03,4862.90,36.06,-112.14,'2/26/1919','The Grand Canyon, carved by the mighty Colorado River, is 277 miles (446 km) long, up to 1 mile (1.6 km) deep, and up to 15 miles (24 km) wide. Millions of years of erosion have exposed the multicolored layers of the Colorado Plateau in mesas and canyon walls, visible from both the north and south rims, or from a number of trails that descend into the canyon itself.','https://www.nps.gov/grca/index.htm','Arizona','Grand Canyon','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg/320px-Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg','park_grand-canyon',5969811);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (310043.96,1254.70,43.73,-110.8,'2/26/1929','Grand Teton is the tallest mountain in the Teton Range. The park''s historic Jackson Hole and reflective piedmont lakes teem with endemic wildlife, with a backdrop of craggy mountains that rise abruptly from the sage-covered valley.','https://www.nps.gov/grte/index.htm','Wyoming','Grand Teton','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Barns_grand_tetons.jpg/320px-Barns_grand_tetons.jpg','park_grand-teton',3270076);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (77180.00,312.30,38.98,-114.3,'10/27/1986','Based around Nevada''s second tallest mountain, Wheeler Peak, Great Basin National Park contains 5,000-year-old bristlecone pines, a rock glacier, and the limestone Lehman Caves. Due to its remote location, the park has some of the country''s darkest night skies. Wildlife includes the Townsend''s big-eared bat, pronghorn, and Bonneville cutthroat trout.','https://www.nps.gov/grba/index.htm','Nevada','Great Basin','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Stella_Lake_Great_Basin.jpg/320px-Stella_Lake_Great_Basin.jpg','park_great-basin',144846);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (107341.87,434.40,37.73,-105.51,'9/13/2004','The tallest sand dunes in North America, up to 750 feet (230 m) tall, were formed by deposits of the ancient Rio Grande in the San Luis Valley. Abutting a variety of grasslands, shrublands, and wetlands, the park also has alpine lakes, six 13,000-foot mountains, and old-growth forests.','https://www.nps.gov/grsa/index.htm','Colorado','Great Sand Dunes','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Great_Sand_Dunes_National_Park_and_Preserve%2C_United_States_%28Unsplash%29.jpg/320px-Great_Sand_Dunes_National_Park_and_Preserve%2C_United_States_%28Unsplash%29.jpg','park_great-sand-dunes',388308);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (522426.88,2114.20,35.68,-83.53,'6/15/1934','The Great Smoky Mountains, part of the Appalachian Mountains, span a wide range of elevations, making them home to over 400 vertebrate species, 100 tree species, and 5000 plant species. Hiking is the park''s main attraction, with over 800 miles (1,300 km) of trails, including 70 miles (110 km) of the Appalachian Trail. Other activities include fishing, horseback riding, and touring nearly 80 historic structures.','https://www.nps.gov/grsm/index.htm','Tennessee','Great Smoky Mountains','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/View_atop_Cliff_Tops_on_Mount_LeConte%2C_GSMNP%2C_TN.jpg/320px-View_atop_Cliff_Tops_on_Mount_LeConte%2C_GSMNP%2C_TN.jpg','park_great-smoky-mountains',11312786);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (86367.10,349.50,31.92,-104.87,'10/15/1966','This park contains Guadalupe Peak, the highest point in Texas, as well as the scenic McKittrick Canyon filled with bigtooth maples, a corner of the arid Chihuahuan Desert, and a fossilized coral reef from the Permian era.','https://www.nps.gov/gumo/index.htm','Texas','Guadalupe Mountains','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Guadalupe_Peak_from_Hunter_Peak.jpg/320px-Guadalupe_Peak_from_Hunter_Peak.jpg','park_guadalupe-mountains',181839);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (33264.62,134.60,20.72,-156.17,'8/1/1916','The Haleakala volcano on Maui features a very large crater with numerous cinder cones, Hosmer''s Grove of alien trees, the Kipahulu section''s scenic pools of freshwater fish, and the native Hawaiian goose. It is home to the greatest number of endangered species within a U.S. National Park.','https://www.nps.gov/hale/index.htm','Hawaii','Haleakala','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Haleakal%C4%81_2017%283%29.jpg/320px-Haleakal%C4%81_2017%283%29.jpg','park_haleakala',1263558);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (323431.38,1308.90,19.38,-155.2,'8/1/1916','This park on the Big Island protects the Kīlauea and Mauna Loa volcanoes, two of the world''s most active geological features. Diverse ecosystems range from tropical forests at sea level to barren lava beds at more than 13,000 feet (4,000 m).','https://www.nps.gov/havo/index.htm','Hawaii','Hawaii Volcanoes','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/P%C4%81hoehoe_and_Aa_flows_at_Hawaii.jpg/320px-P%C4%81hoehoe_and_Aa_flows_at_Hawaii.jpg','park_hawaii-volcanoes',1887580);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (5549.10,22.50,34.51,-93.05,'3/4/1921','Hot Springs was established by act of Congress as a federal reserve on April 20, 1832. As such it is the oldest park managed by the National Park Service. Congress changed the reserve''s designation to National Park on March 4, 1921 after the National Park Service was established in 1916. Hot Springs is the smallest and only National Park in an urban area and is based around natural hot springs that flow out of the low lying Ouachita Mountains. The springs provide opportunities for relaxation in an historic setting; Bathhouse Row preserves numerous examples of 19th-century architecture.','https://www.nps.gov/hosp/index.htm','Arkansas','Hot Springs','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Downtown_Hot_Springs%2C_Arkansas_%28aerial%29.jpg/320px-Downtown_Hot_Springs%2C_Arkansas_%28aerial%29.jpg','park_hot-springs',1544300);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (571790.11,2314.00,48.1,-88.55,'4/3/1940','The largest island in Lake Superior is a place of isolation and wilderness. Along with its many shipwrecks, waterways, and hiking trails, the park also includes over 400 smaller islands within 4.5 miles (7.2 km) of its shores. There are only 20 mammal species on the entire island, though the relationship between its wolf and moose populations is especially unique.','https://www.nps.gov/isro/index.htm','Michigan','Isle Royale','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Isle_Royale.jpg/320px-Isle_Royale.jpg','park_isle-royale',24966);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (790635.74,3199.60,33.79,-115.9,'10/31/1994','Covering large areas of the Colorado and Mojave Deserts and the Little San Bernardino Mountains, this desert landscape is populated by vast stands of Joshua trees. Large changes in elevation reveal various contrasting environments including bleached sand dunes, dry lakes, rugged mountains, and maze-like clusters of monzogranite monoliths.','https://www.nps.gov/jotr/index.htm','California','Joshua Tree','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Joshua_Tree_-_Cyclops_%2B_Potato_Head_-_Sunrise.jpg/320px-Joshua_Tree_-_Cyclops_%2B_Potato_Head_-_Sunrise.jpg','park_joshua-tree',2505286);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (3674529.33,14870.30,58.5,-155,'12/2/1980','This park on the Alaska Peninsula protects the Valley of Ten Thousand Smokes, an ash flow formed by the 1912 eruption of Novarupta, as well as Mount Katmai. Over 2,000 grizzly bears come here each year to catch spawning salmon. Other wildlife includes caribou, wolves, moose, and wolverines.','https://www.nps.gov/katm/index.htm','Alaska','Katmai','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Katmai_Crater_1980.jpg/320px-Katmai_Crater_1980.jpg','park_katmai',37818);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (669983.65,2711.30,59.92,-149.65,'12/2/1980','Near Seward on the Kenai Peninsula, this park protects the Harding Icefield and at least 38 glaciers and fjords stemming from it. The only area accessible to the public by road is Exit Glacier; the rest must be viewed or reached from boat tours.','https://www.nps.gov/kefj/index.htm','Alaska','Kenai Fjords','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Kenai_Fjords_coast.jpg/320px-Kenai_Fjords_coast.jpg','park_kenai-fjords',346534);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (461901.20,1869.20,36.8,-118.55,'3/4/1940','Home to several giant sequoia groves and the General Grant Tree, the world''s second largest measured tree, this park also features part of the Kings River, sculptor of the dramatic granite canyon that is its namesake, and the San Joaquin River, as well as Boyden Cave.','https://www.nps.gov/seki/index.htm','California','Kings Canyon','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/KingsCanyonNP.JPG/320px-KingsCanyonNP.JPG','park_kings-canyon',607479);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (1750716.16,7084.90,67.55,-159.28,'12/2/1980','Kobuk Valley protects 61 miles (98 km) of the Kobuk River and three regions of sand dunes. Created by glaciers, the Great Kobuk, Little Kobuk, and Hunt River Sand Dunes can reach 100 feet (30 m) high and 100 °F (38 °C), and they are the largest dunes in the Arctic. Twice a year, half a million caribou migrate through the dunes and across river bluffs that expose well-preserved ice age fossils.','https://www.nps.gov/kova/index.htm','Alaska','Kobuk Valley','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Kobuk_Bendlova_235.jpg/320px-Kobuk_Bendlova_235.jpg','park_kobuk-valley',15500);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (2619816.49,10602.00,60.97,-153.42,'12/2/1980','The region around Lake Clark features four active volcanoes, including Mount Redoubt, as well as an abundance of rivers, glaciers, and waterfalls. Temperate rainforests, a tundra plateau, and three mountain ranges complete the landscape.','https://www.nps.gov/lacl/index.htm','Alaska','Lake Clark','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Lake_Clark.JPG/320px-Lake_Clark.JPG','park_lake-clark',21102);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (106589.02,431.40,40.49,-121.51,'8/9/1916','Lassen Peak, the largest plug dome volcano in the world, is joined by all three other types of volcanoes in this park: shield, cinder dome, and composite. Though Lassen itself last erupted in 1915, most of the rest of the park is continuously active. Numerous hydrothermal features, including fumaroles, boiling pools, and bubbling mud pots, are heated by molten rock from beneath the peak.','https://www.nps.gov/lavo/index.htm','California','Lassen Volcanic','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Lassen_Peak_and_Lake_Helen.jpg/320px-Lassen_Peak_and_Lake_Helen.jpg','park_lassen-volcanic',536068);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (52830.19,213.80,37.18,-86.1,'7/1/1941','With more than 400 miles (640 km) of passageways explored, Mammoth Cave is the world''s longest known cave system. Subterranean wildlife includes eight bat species, Kentucky cave shrimp, Northern cavefish, and cave salamanders. Above ground, the park provides recreation on the Green River, 70 miles of hiking trails, and plenty of sinkholes and springs.','https://www.nps.gov/maca/index.htm','Kentucky','Mammoth Cave','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Mammoth_Cave_Rotunda_%28USGS_Lwt02830%29.jpg/320px-Mammoth_Cave_Rotunda_%28USGS_Lwt02830%29.jpg','park_mammoth-cave',586514);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (52485.17,212.40,37.18,-108.49,'6/29/1906','This area constitutes over 4,000 archaeological sites of the Ancestral Puebloan people, who lived here and elsewhere in the Four Corners region for at least 700 years. Cliff dwellings built in the 12th and 13th centuries include Cliff Palace, which has 150 rooms and 23 kivas, and the Balcony House, with its many passages and tunnels.','https://www.nps.gov/meve/index.htm','Colorado','Mesa Verde','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Mesa_verde_north_2007.jpg/320px-Mesa_verde_north_2007.jpg','park_mesa-verde',583527);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (236381.64,956.60,46.85,-121.75,'3/2/1899','Mount Rainier, an active stratovolcano, is the most prominent peak in the Cascades and is covered by 26 named glaciers including Carbon Glacier and Emmons Glacier, the largest in the contiguous United States. The mountain is popular for climbing, and more than half of the park is covered by subalpine and alpine forests and meadows seasonally in bloom with wildflowers. Paradise on the south slope is the snowiest place on Earth where snowfall is measured regularly. The Longmire visitor center is the start of the Wonderland Trail, which encircles the mountain.','https://www.nps.gov/mora/index.htm','Washington','Mount Rainier','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG/320px-Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG','park_mount-rainier',1356913);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (504780.94,2042.80,48.7,-121.2,'10/2/1968','This complex encompasses two units of the National Park itself as well as the Ross Lake and Lake Chelan National Recreation Areas. The highly glaciated mountains are spectacular examples of Cascade geology. Popular hiking and climbing areas include Cascade Pass, Mount Shuksan, Mount Triumph, and Eldorado Peak.','https://www.nps.gov/noca/index.htm','Washington','North Cascades','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cascade_Pass_and_Pelton_Basin.jpg/320px-Cascade_Pass_and_Pelton_Basin.jpg','park_north-cascades',28646);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (922650.10,3733.80,47.97,-123.5,'6/29/1938','Situated on the Olympic Peninsula, this park includes a wide range of ecosystems from Pacific shoreline to temperate rainforests to the alpine slopes of the Olympic Mountains, the tallest of which is Mount Olympus. The Hoh Rainforest and Quinault Rainforest are the wettest area in the contiguous United States, with the Hoh receiving an average of almost 12 ft (3.7 m) of rain every year.','https://www.nps.gov/olym/index.htm','Washington','Olympic','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cedar_Creek_Abbey_Island_Ruby_Beach.jpg/320px-Cedar_Creek_Abbey_Island_Ruby_Beach.jpg','park_olympic',3390221);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (221415.77,896.00,35.07,-109.78,'12/9/1962','This portion of the Chinle Formation has a large concentration of 225-million-year-old petrified wood. The surrounding Painted Desert features eroded cliffs of red-hued volcanic rock called bentonite. Dinosaur fossils and over 350 Native American sites are also protected in this park.','https://www.nps.gov/pefo/index.htm','Arizona','Petrified Forest','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/The_PEFO_Tepees.jpg/320px-The_PEFO_Tepees.jpg','park_petrified-forest',643274);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (26685.73,108.00,36.48,-121.16,'1/10/2013','Named for the eroded leftovers of a portion of an extinct volcano, the park''s massive black and gold monoliths of andesite and rhyolite are a popular destination for rock climbers. Hikers have access to trails crossing the Coast Range wilderness. The park is home to the endangered California condor (Gymnogyps californianus) and one of the few locations in the world where these extremely rare birds can be seen in the wild. Pinnacles also supports a dense population of prairie falcons, and more than 13 species of bat which populate its talus caves.','https://www.nps.gov/pinn/index.htm','California','Pinnacles','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Rock_formations_at_Pinnacles_National_Park.jpg/320px-Rock_formations_at_Pinnacles_National_Park.jpg','park_pinnacles',215555);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (138999.37,562.50,41.3,-124,'10/2/1968','This park and the co-managed state parks protect almost half of all remaining coastal redwoods, the tallest trees on earth. There are three large river systems in this very seismically active area, and 37 miles (60 km) of protected coastline reveal tide pools and seastacks. The prairie, estuary, coast, river, and forest ecosystems contain a wide variety of animal and plant species.','https://www.nps.gov/redw/index.htm','California','Redwood','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Redwood_National_Park%2C_fog_in_the_forest.jpg/320px-Redwood_National_Park%2C_fog_in_the_forest.jpg','park_redwood',536297);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (265795.20,1075.60,40.4,-105.58,'1/26/1915','Bisected north to south by the Continental Divide, this portion of the Rockies has ecosystems varying from over 150 riparian lakes to montane and subalpine forests to treeless alpine tundra. Wildlife including mule deer, bighorn sheep, black bears, and cougars inhabit its igneous mountains and glacial valleys. Longs Peak, a classic Colorado fourteener, and the scenic Bear Lake are popular destinations, as well as the historic Trail Ridge Road, which reaches an elevation of more than 12,000 feet (3,700 m).','https://www.nps.gov/romo/index.htm','Colorado','Rocky Mountain','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rocky_Mountain_National_Park_in_September_2011_-_Glacier_Gorge_from_Bear_Lake.JPG/320px-Rocky_Mountain_National_Park_in_September_2011_-_Glacier_Gorge_from_Bear_Lake.JPG','park_rocky-mountain',4517585);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (91715.72,371.20,32.25,-110.5,'10/14/1994','Split into the separate Rincon Mountain and Tucson Mountain districts, this park is evidence that the dry Sonoran Desert is still home to a great variety of life spanning six biotic communities. Beyond the namesake giant saguaro cacti, there are barrel cacti, chollas, and prickly pears, as well as lesser long-nosed bats, spotted owls, and javelinas.','https://www.nps.gov/sagu/index.htm','Arizona','Saguaro','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Saguaro_Sunset.jpg/320px-Saguaro_Sunset.jpg','park_saguaro',820426);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (404062.63,1635.20,36.43,-118.68,'9/25/1890','This park protects the Giant Forest, which boasts some of the world''s largest trees, the General Sherman being the largest measured tree in the park. Other features include over 240 caves, a long segment of the Sierra Nevada including the tallest mountain in the contiguous United States, and Moro Rock, a large granite dome.','https://www.nps.gov/seki/index.htm','California','Sequoia','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/General_Sherman_Tree_in_Sequoia_National_Park_-_June_2022.jpg/180px-General_Sherman_Tree_in_Sequoia_National_Park_-_June_2022.jpg','park_sequoia',1254688);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (199195.27,806.10,38.53,-78.35,'12/26/1935','Shenandoah''s Blue Ridge Mountains are covered by hardwood forests that teem with a wide variety of wildlife. The Skyline Drive and Appalachian Trail run the entire length of this narrow park, along with more than 500 miles (800 km) of hiking trails passing scenic overlooks and cataracts of the Shenandoah River.','https://www.nps.gov/shen/index.htm','Virginia','Shenandoah','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Skyline_Drive_in_the_Fall_%2821852619608%29.jpg/320px-Skyline_Drive_in_the_Fall_%2821852619608%29.jpg','park_shenandoah',1437341);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (70446.89,285.10,46.97,-103.45,'11/10/1978','This region that enticed and influenced President Theodore Roosevelt consists of a park of three units in the northern badlands. Besides Roosevelt''s historic cabin, there are numerous scenic drives and backcountry hiking opportunities. Wildlife includes American bison, pronghorn, bighorn sheep, and wild horses.','https://www.nps.gov/thro/index.htm','North Dakota','Theodore Roosevelt','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/View_of_Theodore_Roosevelt_National_Park.jpg/320px-View_of_Theodore_Roosevelt_National_Park.jpg','park_theodore-roosevelt',753880);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (14948.46,60.50,18.33,-64.73,'8/2/1956','This island park on Saint John preserves Taíno archaeological sites and the ruins of sugar plantations from Columbus''s time, as well as all the natural environs. Surrounding the pristine beaches are mangrove forests, seagrass beds, and coral reefs.','https://www.nps.gov/viis/index.htm','US Virgin Islands','Virgin Islands','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/St_John_Trunk_Bay_3.jpg/320px-St_John_Trunk_Bay_3.jpg','park_virgin-islands',411343);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (218200.15,883.00,48.5,-92.88,'1/8/1971','This park protecting four lakes near the Canada–US border is a site for canoeing, kayaking, and fishing. The park also preserves a history populated by Ojibwe Native Americans, French fur traders called voyageurs, and gold miners. Formed by glaciers, the region features tall bluffs, rock gardens, islands, bays, and several historic buildings.','https://www.nps.gov/voya/index.htm','Minnesota','Voyageurs','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Voyageurs_National_Park.jpg/800px-Voyageurs_National_Park.jpg','park_voyageurs',241912);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (33970.84,137.50,43.57,-103.48,'1/9/1903','Wind Cave is distinctive for its calcite fin formations called boxwork, a unique formation rarely found elsewhere, and needle-like growths called frostwork. The cave is one of the longest and most complex caves in the world. Above ground is a mixed-grass prairie with animals such as bison, black-footed ferrets, and prairie dogs, and ponderosa pine forests that are home to cougars and elk. The cave is culturally significant to the Lakota people as the site ''from which Wakan Tanka, the Great Mystery, sent the buffalo out into their hunting grounds.''','https://www.nps.gov/wica/index.htm','South Dakota','Wind Cave','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cave_Boxwork_often_call_cratework_when_this_large._WInd_Cave.JPG/320px-Cave_Boxwork_often_call_cratework_when_this_large._WInd_Cave.JPG','park_wind-cave',617377);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (8323146.48,33682.60,61,-142,'12/2/1980','An over 8 million acres (32,375 km2) plot of mountainous country—the largest National Park in the system—protects the convergence of the Alaska, Chugach, and Wrangell-Saint Elias Ranges, which include many of the continent''s tallest mountains and volcanoes, including the 18,008-foot Mount Saint Elias. More than a quarter of the park is covered with glaciers, including the tidewater Hubbard Glacier, piedmont Malaspina Glacier, and valley Nabesna Glacier.','https://www.nps.gov/wrst/index.htm','Alaska','Wrangell St. Elias','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Malaspina_Glacier_from_space.jpg/320px-Malaspina_Glacier_from_space.jpg','park_wrangell-st-elias',79047);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (2219790.71,8983.20,44.6,-110.5,'3/1/1872','Situated on the Yellowstone Caldera, the park has an expansive network of geothermal areas including boiling mud pots, vividly colored hot springs such as Grand Prismatic Spring, and regularly erupting geysers, the best-known being Old Faithful. The yellow-hued Grand Canyon of the Yellowstone River contains several high waterfalls, while four mountain ranges traverse the park. More than 60 mammal species including gray wolves, grizzly bears, black bears, lynxes, bison, and elk, make this park one of the best wildlife viewing spots in the country.','https://www.nps.gov/yell/index.htm','Wyoming','Yellowstone','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Grand_Canyon_of_yellowstone.jpg/180px-Grand_Canyon_of_yellowstone.jpg','park_yellowstone',4257177);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (761747.50,3082.70,37.83,-119.5,'10/1/1890','Yosemite features sheer granite cliffs, exceptionally tall waterfalls, and old-growth forests at a unique intersection of geology and hydrology. Half Dome and El Capitan rise from the park''s centerpiece, the glacier-carved Yosemite Valley, and from its vertical walls drop Yosemite Falls, one of North America''s tallest waterfalls at 2,425 feet (739 m) high. Three giant sequoia groves, along with a pristine wilderness in the heart of the Sierra Nevada, are home to a wide variety of rare plant and animal species.','https://www.nps.gov/yose/index.htm','California','Yosemite','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Tunnel_View%2C_Yosemite_Valley%2C_Yosemite_NP_-_Diliff.jpg/320px-Tunnel_View%2C_Yosemite_Valley%2C_Yosemite_NP_-_Diliff.jpg','park_yosemite',5028868);
INSERT INTO NationalParkList(park_area_acres,park_area_sq_km,park_lat,park_long,park_date_est,park_description,nps_link,park_state,park_name,pic_license,pic_url,park_code,park_visitors) VALUES (147237.02,595.80,37.3,-113.05,'11/19/1919','Located at the junction of the Colorado Plateau, Great Basin, and Mojave Desert, this park contains sandstone features such as mesas, rock towers, and canyons, including the Virgin River Narrows. The various sandstone formations and the forks of the Virgin River create a wilderness divided into four ecosystems: desert, riparian, woodland, and coniferous forest.','https://www.nps.gov/zion/index.htm','Utah','Zion','https://creativecommons.org/licenses/by-sa/3.0/legalcode','https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zion_angels_landing_view.jpg/234px-Zion_angels_landing_view.jpg','park_zion',4295127);


USE [RetoolSampleDataDB]
GO

ALTER TABLE [dbo].[NationalParkList] 
DROP CONSTRAINT PK_NationalParkList;
GO

ALTER TABLE [dbo].[NationalParkList]
ADD ID2 int NULL;
GO

UPDATE [dbo].[NationalParkList] SET [dbo].[NationalParkList].ID2 = [dbo].[NationalParkList].ID
GO

ALTER TABLE [dbo].[NationalParkList]
DROP COLUMN ID;
GO

EXEC sp_rename 'dbo.NationalParkList.ID2', 'ID', 'COLUMN';

PRINT 'SCRIPT EXECUTION COMPLETED';